config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :students
  get 'home/index'
  root 'home#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

             has_many :students
        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
    
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /students or /students.json
  def index
    @students = Student.all.includes(:user)  # Include user association for efficiency
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    # @student = Student.new
    @student = current_user.students.build
  end

  # GET /students/1/edit
  def edit

  end

  # POST /students or /students.json
  def create
    # @student = Student.new(student_params)

    @student = current_user.students.build(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy!

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @student = current_user.students.find_by(id: params[:id]) 
    redirect_to student_path, notice: "Not authorized to edit this student" if @student.nil?  # Correct nil check
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :email, :age, :major, :gpa, :year_of_graduation, :address, :phone_number, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to "College Student App", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "All Students Record", students_path, class: "nav-link" %>
        </li>

        

        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "Add New Student", new_student_path, class: "nav-link" %>
        </li>
        
          <li class="nav-item">
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
</li>

          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About Us </h1>

app/views/home/index.html.erb
<h1> Hello World! </h1>
<p>This is my First rails webpage </p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>College Student App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <br/>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :major, style: "display: block" %>
    <%= form.text_field :major %>
  </div>

  <div>
    <%= form.label :gpa, style: "display: block" %>
    <%= form.text_field :gpa %>
  </div>

  <div>
    <%= form.label :year_of_graduation, style: "display: block" %>
    <%= form.number_field :year_of_graduation %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

<div>
    
    <%= form.number_field :user_id, id: :student_id, value: current_user.id, type: :hidden %>
  </div>
 
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= student.age %>
  </p>

  <p>
    <strong>Major:</strong>
    <%= student.major %>
  </p>

  <p>
    <strong>Gpa:</strong>
    <%= student.gpa %>
  </p>

  <p>
    <strong>Year of graduation:</strong>
    <%= student.year_of_graduation %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= student.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= student.phone_number %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<% if notice %>
  <p style="color: green"><%= notice %></p>
<% end %>

<h1>All Students List</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">User ID</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
        <td><%= student.id %></td>
        <td>
          <%= link_to "Show", student %> |
          <%= link_to "Edit", edit_student_path(student) %> |
          <%= link_to "Delete", student, method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %> </tbody>
</table>

<%= link_to "New student", new_student_path, class: "btn btn-secondary" %>

app/views/students/new.html.erb
<h1> Add New students </h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<div class="container">
  <p class="notice"><%= notice %></p>

  <%= render @student %>

  <div class="btn-group">
    <%= link_to "Edit", edit_student_path(@student), class: "btn btn-secondary" %>
    <%= link_to "Back to Students", students_path, class: "btn btn-secondary" %>
    <%= button_to "Destroy", @student, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
  </div>
</div>